### ISSUE TITLE
Navigation items: Finger appears, but only triggers on font click

### ISSUE THREAD

**Issue by Werninator** [hew/hew.tools#1]
Don't know if it's intentional but

![bildschirmfoto 2017-12-20 um 14 48 04](https://user-images.githubusercontent.com/6310506/34210107-fa2e2396-e594-11e7-883e-6151ab2d098d.png)

* green => finger appears, click doesn't do anything
* blue  => finger appears, click does navigate the page

**Comment by hew** [comment]
Closing this issue because it applies to a no-longer-active branch. Thanks for reporting.
