### ISSUE TITLE
Reusing Routing In ReactNative

### ISSUE THREAD

**Issue by idkjs** [hew/hew.tools#2]
Hi @hew! I am wondering if you have figured out how to reuse your routing on the App side? I tried using your set up as a guide, got the routing going on web using your fork of bs-react-navigation. I then make the try to create a nav module for web and get the following error:

```
>>>> Start compiling
[1/1] Building src/mobile/SwitchNavMobile-Gitphone.cmj

  We've found a bug for you!
  /Users/prisc_000/working/RNWEB/gitphone/src/mobile/SwitchNavMobile.re 13:26-25:3

  11 │ };
  12 │ module Stack =
  13 │   SwitchNavigator.Create({
  14 │     open SwitchNavigator;
   . │ ...
  24 │       };
  25 │   });
  26 │
  27 │

  Signature mismatch:
  ...
  Values do not match:
    let getScreen:
      (Config.route, Gitphone.Routes.navigation) =>
      (ReasonReact.reactElement,
      BsReactNavigation.SwitchNavigator.screenOptions)
  is not included in
    let getScreen:
      (route, BsReactNavigation.SwitchNavigator.navigation(route)) =>
      (ReasonReact.reactElement,
      BsReactNavigation.SwitchNavigator.screenOptions)
  File "/Users/prisc_000/working/RNWEB/gitphone/src/mobile/SwitchNavMobile.re", line 20, characters 9-18:
    Actual declaration

>>>> Finish compiling(exit: 1)
```
here is the module in which I recreate the Routes module locally so I can redefine the `navigation` using the regular SwitchNavigator:
```
open BsReactNavigation;

module Config =  {
  // open BsReactNavigation;

  type route =
    | Home
    | CommitList;

  type navigation = SwitchNavigator.navigation(route);
};
module Stack =
  SwitchNavigator.Create({
    open SwitchNavigator;
    // open Routes;
     type route = Routes.route;

    let initialRoute:route = Home;

    let getScreen = (~route, navigation) =>
      switch (route:route) {
      | Home => (<Home navigation />, screenOptions(~title="Home", ()))
      | CommitList => (<CommitList navigation />, screenOptions(~title="CommitList", ()))
      };
  });


let app = Stack.render;


```

If you are so inclined, would you mind sharing a word on how to think about handling this? Just hoping to learn something. Thanks for the project, either way.

Peace to you.

**Comment by hew** [comment]
You figure it out, Alain?

**Comment by idkjs** [comment]
Not really, brother. Though I had. Figuring I have to set up bsconfig to compile each directory then maybe import the module? Is that about right?

**Comment by hew** [comment]
I haven't really figured this out too well myself, either. Now that expo has the web support, I may just use their routing.

**Comment by idkjs** [comment]
Wow, didnt know that about expo. I need to check that out.

So routing seems to be the issue. If you dont need routing, seems like you can get something to show up on both web and RN pretty easily...

**Comment by hew** [comment]
Yeah pretty much!

**Comment by hew** [comment]
@idkjs, 

I think this is the issue: 

```reasonml
 type route = Routes.route;
```

Shouldn't it be

```reasonml
 type route = Config.route;
```

?

**Comment by hew** [comment]
If `Routes.route` is your file for the web stuff, then that would throw off the type signatures for the app routing in the file you have pictured (I think).

**Comment by hew** [comment]
> I may just use their routing.

Cause they don't really have routing. The demo I saw was using react-navigation under the hood. So what you have _should_ work in theory. 

I am somewhat close to releasing a small "real-world" `reasonml-react-navigation` repo that has nested routers and stuff like that. So you and others can see how this is all put together. My webite is only partially there. 

I'll let you know when it's out.

**Comment by idkjs** [comment]
Standing by, brother. Always a pleasure to read your code.
